Repository OjasMittal/TechBlogzz, pull requests merged in 2023-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: good first issue, hacktoberfest2023, hacktoberfest-accespted

#3 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accespted

#4 Ojas mittal patch 1
  ML/What is ML?
  README.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#6 Completed the necessary changes after the review (Deleted jpegs and python files)
  Computer-Vision-Introduction/Introduction-to-Computer-Vision.md
  Computer-Vision-Introduction/Various-Image-Processing-Techniques.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#8 Add new content on Artificial Neural Network.
  ANN_in_ML/ANN.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#10 Simranroy01 patch 2
  AI/ArtificialIntelligence.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#11 Add new content on Python-basics
  python_basics/python-basics.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#14 feat: Blog on Kali Linux
  Kali_Linux/Usage.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#15 Added content in Computer Vision
  Computer-Vision-Introduction/Digital-Image-Processing.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#19 Want to add C++ Blog
  C++/C++-basics.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#20 feat: Guide for Burp Suite Community Edition
  Kali_Linux/Burp_Suite.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#21 New branch pragya
  Python/PythonStringMethods.md
  PythonStringFunctions
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#22 Crypto Blog
  Crypto/cryptocurrency.md
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#23 Create NLP
  AI/NLP.md
  AI/NLP2.md
  AI/NaturalProcessingLanguage.md
  NLP
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#24 Create Internet of Things.md
  IOT/Internet of Things.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accespted

#29 Update C++-basics.md
  C++/C++-basics.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accespted
